#!/usr/bin/env python3
"""Generate compact ORB reference descriptors for the bundled card catalog.

The runtime recognizer should not decode 19 JPEGs and recompute their ORB
features every time the app starts. This script preprocesses the canonical card
images exactly once and emits a TypeScript data module consumed by the mobile
worklet.

Run with OpenCV 4.12 to match the Android runtime used by
react-native-fast-opencv 1.x:

    python -m pip install opencv-python-headless==4.12.0.88 numpy
    python scripts/generate_orb_reference_descriptors.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "data/cards/legends-of-laar.json"
OUTPUT_PATH = (
    ROOT
    / "src/infrastructure/recognition/orb/referenceDescriptors.generated.ts"
)
REPORT_PATH = ROOT / "docs/orb-reference-validation.md"

NORMALIZED_WIDTH = 252
NORMALIZED_HEIGHT = 356
ORB_NFEATURES = 600
ORB_SCALE_FACTOR = 1.2
ORB_NLEVELS = 8
ORB_EDGE_THRESHOLD = 15
ORB_FIRST_LEVEL = 0
ORB_WTA_K = 2
ORB_PATCH_SIZE = 31
ORB_FAST_THRESHOLD = 10
RATIO_TEST = 0.75


def create_orb() -> cv2.ORB:
    return cv2.ORB_create(
        nfeatures=ORB_NFEATURES,
        scaleFactor=ORB_SCALE_FACTOR,
        nlevels=ORB_NLEVELS,
        edgeThreshold=ORB_EDGE_THRESHOLD,
        firstLevel=ORB_FIRST_LEVEL,
        WTA_K=ORB_WTA_K,
        scoreType=cv2.ORB_HARRIS_SCORE,
        patchSize=ORB_PATCH_SIZE,
        fastThreshold=ORB_FAST_THRESHOLD,
    )


def load_normalized_grayscale(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
    if image is None:
        raise RuntimeError(f"Could not read card image: {path}")
    return cv2.resize(
        image,
        (NORMALIZED_WIDTH, NORMALIZED_HEIGHT),
        interpolation=cv2.INTER_AREA,
    )


def descriptors_for(orb: cv2.ORB, image: np.ndarray) -> np.ndarray:
    _keypoints, descriptors = orb.detectAndCompute(image, None)
    if descriptors is None or descriptors.shape[0] == 0:
        raise RuntimeError("ORB produced no descriptors")
    if descriptors.shape[1] != 32:
        raise RuntimeError(f"Unexpected ORB descriptor width: {descriptors.shape}")
    return descriptors


def good_match_count(
    matcher: cv2.BFMatcher,
    query: np.ndarray,
    reference: np.ndarray,
) -> int:
    groups = matcher.knnMatch(query, reference, k=2)
    good = 0
    for group in groups:
        if len(group) < 2:
            continue
        best, second = group
        if best.distance < RATIO_TEST * second.distance:
            good += 1
    return good


def make_variant(image: np.ndarray, card_index: int, variant_index: int) -> np.ndarray:
    """Create deterministic camera-ish distortions for a coarse offline sanity check."""
    rng = np.random.default_rng(seed=card_index * 1000 + variant_index)
    height, width = image.shape

    inset_x = width * 0.045
    inset_y = height * 0.035
    source = np.float32(
        [[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]]
    )
    jitter = np.float32(
        [
            [rng.uniform(0, inset_x), rng.uniform(0, inset_y)],
            [rng.uniform(-inset_x, 0), rng.uniform(0, inset_y)],
            [rng.uniform(-inset_x, 0), rng.uniform(-inset_y, 0)],
            [rng.uniform(0, inset_x), rng.uniform(-inset_y, 0)],
        ]
    )
    destination = source + jitter
    matrix = cv2.getPerspectiveTransform(source, destination)
    warped = cv2.warpPerspective(
        image,
        matrix,
        (width, height),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_REPLICATE,
    )

    angle = float(rng.uniform(-5.0, 5.0))
    rotation = cv2.getRotationMatrix2D((width / 2, height / 2), angle, 1.0)
    warped = cv2.warpAffine(
        warped,
        rotation,
        (width, height),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_REPLICATE,
    )

    alpha = float(rng.uniform(0.72, 1.18))
    beta = float(rng.uniform(-18, 18))
    warped = cv2.convertScaleAbs(warped, alpha=alpha, beta=beta)

    if variant_index % 3 == 0:
        warped = cv2.GaussianBlur(warped, (3, 3), 0)

    return warped


def write_generated_module(entries: list[dict[str, Any]]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    encoded_entries: list[str] = []
    for entry in entries:
        data = ",".join(str(value) for value in entry["data"])
        encoded_entries.append(
            "  {"
            f"cardId:{json.dumps(entry['cardId'])},"
            f"rows:{entry['rows']},cols:32,data:[{data}]"
            "}"
        )

    output = "\n".join(
        [
            "// AUTO-GENERATED by scripts/generate_orb_reference_descriptors.py.",
            "// Do not edit by hand.",
            "",
            "export type OrbReferenceDescriptor = {",
            "  readonly cardId: string;",
            "  readonly rows: number;",
            "  readonly cols: 32;",
            "  readonly data: readonly number[];",
            "};",
            "",
            "export const ORB_REFERENCE_DESCRIPTORS: readonly OrbReferenceDescriptor[] = [",
            ",\n".join(encoded_entries),
            "];",
            "",
        ]
    )
    OUTPUT_PATH.write_text(output, encoding="utf-8")


def percentile(values: list[float], p: float) -> float:
    if not values:
        return math.nan
    return float(np.percentile(np.asarray(values, dtype=np.float64), p))


def write_validation_report(
    catalog: list[dict[str, Any]],
    references: list[np.ndarray],
    images: list[np.ndarray],
) -> None:
    orb = create_orb()
    matcher = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)
    correct = 0
    total = 0
    correct_good_counts: list[float] = []
    false_good_counts: list[float] = []
    margins: list[float] = []
    failures: list[str] = []

    variants_per_card = 8
    for card_index, (card, image) in enumerate(zip(catalog, images)):
        for variant_index in range(variants_per_card):
            query_image = make_variant(image, card_index, variant_index)
            query = descriptors_for(orb, query_image)
            scores = [good_match_count(matcher, query, reference) for reference in references]
            ranking = sorted(range(len(scores)), key=lambda index: scores[index], reverse=True)
            best_index = ranking[0]
            second_index = ranking[1]
            total += 1
            best = float(scores[best_index])
            second = float(scores[second_index])
            margins.append(best - second)

            true_score = float(scores[card_index])
            best_false = max(float(score) for idx, score in enumerate(scores) if idx != card_index)
            correct_good_counts.append(true_score)
            false_good_counts.append(best_false)

            if best_index == card_index:
                correct += 1
            else:
                failures.append(
                    f"- {card['id']} variant {variant_index}: predicted "
                    f"{catalog[best_index]['id']} ({int(best)} vs true {int(true_score)})"
                )

    accuracy = correct / total if total else 0.0
    lines = [
        "# ORB reference validation",
        "",
        "Generated by `scripts/generate_orb_reference_descriptors.py`.",
        "This is a deterministic synthetic sanity check, not a substitute for testing physical cards.",
        "",
        f"- OpenCV: `{cv2.__version__}`",
        f"- Normalized card size: `{NORMALIZED_WIDTH}×{NORMALIZED_HEIGHT}`",
        f"- ORB features: `{ORB_NFEATURES}`",
        f"- Lowe ratio: `{RATIO_TEST}`",
        f"- Synthetic variants: `{total}`",
        f"- Top-1 accuracy: `{correct}/{total}` (`{accuracy:.1%}`)",
        f"- True-match good-count p05 / median: `{percentile(correct_good_counts, 5):.1f}` / `{percentile(correct_good_counts, 50):.1f}`",
        f"- Best-false good-count p95 / max: `{percentile(false_good_counts, 95):.1f}` / `{max(false_good_counts):.0f}`",
        f"- Winner margin p05 / median: `{percentile(margins, 5):.1f}` / `{percentile(margins, 50):.1f}`",
        "",
        "## Failures",
        "",
    ]
    lines.extend(failures if failures else ["None in the synthetic validation set."])
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    catalog_document = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    catalog: list[dict[str, Any]] = catalog_document["cards"]
    orb = create_orb()

    references: list[np.ndarray] = []
    images: list[np.ndarray] = []
    entries: list[dict[str, Any]] = []

    for card in catalog:
        image = load_normalized_grayscale(ROOT / card["image"])
        descriptors = descriptors_for(orb, image)
        images.append(image)
        references.append(descriptors)
        entries.append(
            {
                "cardId": card["id"],
                "rows": int(descriptors.shape[0]),
                "data": descriptors.reshape(-1).astype(np.uint8).tolist(),
            }
        )
        print(f"{card['id']}: {descriptors.shape[0]} descriptors")

    write_generated_module(entries)
    write_validation_report(catalog, references, images)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
